# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin Conway Chicago based Front-End Developer
email: justin@conwaydev.com
description: > # this means to ignore newlines until "baseurl:"
  Justin Conway is a Front End Web Developer currently working at Sprout Social
  as a part of the Marketing Development team. He has over 7 years of experience
  solving problems with web technologies and is always looking to contribute to
  challenging and innovative web products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://conwaydev.github.io" # the base hostname & protocol for your site
twitter_username: conwaydev
github_username:  conwaydev

# Build settings
markdown: kramdown
