name: CI

on:
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetches tweets and commits 
      run: yarn && yarn fetch-tweets && git add . && git commit -am "update tweets"
